# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()



DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x07openapi"O\n\rClientRequest\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x11\n\trequestId\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c"J\n\x0e\x43lientResponse\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x32\x43\n\x05Quote\x12:\n\x07request\x12\x16.openapi.ClientRequest\x1a\x17.openapi.ClientResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTREQUEST']._serialized_start=26
  _globals['_CLIENTREQUEST']._serialized_end=105
  _globals['_CLIENTRESPONSE']._serialized_start=107
  _globals['_CLIENTRESPONSE']._serialized_end=181
  _globals['_QUOTE']._serialized_start=183
  _globals['_QUOTE']._serialized_end=250
# @@protoc_insertion_point(module_scope)
